# Generated by Django 3.2.19 on 2023-06-18 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the directory', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Directory creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'directories',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the task', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the task', max_length=1000, null=True)),
                ('date', models.DateField(blank=True, help_text='Targeted date for complete the task', null=True)),
                ('is_important', models.BooleanField(default=False, help_text='Is the task is important or not')),
                ('is_completed', models.BooleanField(default=False, help_text='Is the task is completed or not')),
                ('directory', models.ForeignKey(blank=True, help_text='Task directory', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.directorymodel')),
                ('user', models.ForeignKey(blank=True, help_text='Task creator', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
